### PR TITLE
Add pictures to to what section

### PR DESCRIPTION
**Pull request by Ceasar**
More pictures are better. See:

pictures

### CODE REVIEW

**Comment by Ceasar** [comment]
Also changes headers from h3 to h2 in the what section.

**Comment by yefim** [comment]
There's too much text under the images. Other than that, I love the images.

**Comment by Ceasar** [comment]
The text isn't something I added in this commit. That's its own issue.

**Comment by yefim** [comment]
Alright, agreed. Pictures are A-OK!

**Pull request merged**
